// Generated by CoffeeScript 1.7.1
(function() {
  var addIndentToCharacter, addIndentation, getSelectedText, indentedText, originalText, replaceSelectedText;

  replaceSelectedText = function(originalText, replaceSelectedText) {
    var newString, originalString, textArea;
    textArea = $('.usertext-edit > div > textarea');
    originalString = textArea.val();
    newString = originalString.replace(originalText, replaceSelectedText);
    textArea.val(newString);
  };

  getSelectedText = function() {
    return window.getSelection().toString();
  };

  addIndentToCharacter = function(character, i) {
    if (i === 0) {
      return '    ' + character;
    } else if (character.match(/\r/) || character.match(/\n/)) {
      return character + '    ';
    }
    return character;
  };

  addIndentation = function(text) {
    var arrText, indentedText;
    arrText = text.split('');
    indentedText = arrText.map(addIndentToCharacter);
    return indentedText.join('');
  };

  originalText = getSelectedText();

  indentedText = addIndentation(originalText);

  replaceSelectedText(originalText, indentedText);

  return;

}).call(this);

//# sourceMappingURL=CodeIndentCoffee.map
